// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
- create an ordered group of docs
- render a sidebar for each doc of that group
- provide next/previous navigation

The sidebars can be generated from the filesystem, or explicitly defined here.

Create as many sidebars as you want.

@type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // tutorialSidebar: [
  //   { type: 'autogenerated', dirName: '.' }
  // ],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    // 'hello',
    {
      type: 'category',
      label: 'JavaScript',
      items: [
        'JavaScript/arrayMethods',
        'JavaScript/about-equal',
        'JavaScript/async-await',
        'JavaScript/event-loop',
        'JavaScript/Map',
        'JavaScript/prototype',
        'JavaScript/sort',
        'JavaScript/statements-expression',
        'JavaScript/var-const-let',
        'JavaScript/solvingList',
        {
          type: 'category',
          label: '🌊TypeScript',
          items: [
            'JavaScript/TypeScript/intro',
            'JavaScript/TypeScript/BasicTypes',
            'JavaScript/TypeScript/array-tuple',
            'JavaScript/TypeScript/Enum',
            'JavaScript/TypeScript/DOM',
            'JavaScript/TypeScript/any-unknown',
            'JavaScript/TypeScript/type&type',
            'JavaScript/TypeScript/type&interfaces',
            'JavaScript/TypeScript/function&type',
            'JavaScript/TypeScript/generics&Asynchronous',
            'JavaScript/TypeScript/mapped',
            'JavaScript/TypeScript/tsconfig',
            'JavaScript/TypeScript/daily',
          ],
          link: { type: 'doc', id: 'JavaScript/TypeScript/intro' },
        },
      ],
    },
    {
      type: 'category',
      label: 'solve code',
      items: [{ type: 'autogenerated', dirName: 'solve-code' }],
      className: 'hidden-sidebar-category',
    },
    {
      type: 'category',
      label: 'Vue3 必學知識點',
      items: [{ type: 'autogenerated', dirName: 'Vue-base' }],
      link: {type: 'doc', id: 'Vue-base/intro'},
    },
    {
      type: 'category',
      label: 'Vue Daily',
      items: [{type: 'autogenerated', dirName: 'vue-daily'}],
    },
    {
      type: 'category',
      label: 'Git 手冊',
      items: [{ type: 'autogenerated', dirName: 'git-notes' }],
      link: {type: 'doc', id: 'git-notes/intro'},
    },
    {
      type: 'category',
      label: 'Linux',
      items: [{ type: 'autogenerated', dirName: 'linux' }],
    },
    {
      type: 'category',
      label: '其他',
      items: [{ type: 'autogenerated', dirName: 'else' }],
    },
    // {
    //   type: 'category',
    //   label: 'Solving Code', // 您可以給這個分類一個標籤
    //   items: [{type: 'autogenerated', dirName: 'solving-code'}],
    //   // className: 'hidden-sidebar-category',
    // },
  ],
};

export default sidebars;
