// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
- create an ordered group of docs
- render a sidebar for each doc of that group
- provide next/previous navigation

The sidebars can be generated from the filesystem, or explicitly defined here.

Create as many sidebars as you want.

@type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // tutorialSidebar: [
  //   { type: 'autogenerated', dirName: '.' }
  // ],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    // 'hello',
    {
      type: 'category',
      label: 'JavaScript',
      items: [{ type: 'autogenerated', dirName: 'JavaScript' }],
    },
    {
      type: 'category',
      label: 'solve code',
      items: [{ type: 'autogenerated', dirName: 'solve-code' }],
      className: 'hidden-sidebar-category',
    },
    {
      type: 'category',
      label: 'Vue',
      items: [{type: 'autogenerated', dirName: 'Vue'}],
    },
    {
      type: 'category',
      label: 'Vue Daily',
      items: [{type: 'autogenerated', dirName: 'vue-daily'}],
    },
    {
      type: 'category',
      label: 'Git 手冊',
      items: [{ type: 'autogenerated', dirName: 'git-notes' }],
      link: {type: 'doc', id: 'git-notes/intro'},
    },
    {
      type: 'category',
      label: 'Linux',
      items: [{ type: 'autogenerated', dirName: 'linux' }],
    },
    // {
    //   type: 'category',
    //   label: 'Solving Code', // 您可以給這個分類一個標籤
    //   items: [{type: 'autogenerated', dirName: 'solving-code'}],
    //   // className: 'hidden-sidebar-category',
    // },
  ],
};

export default sidebars;
